// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: FezaESPArayuz

#include "ui.h"
#include "ui_helpers.h"

extern int breadCount;
extern int pastaCount;
extern int diaperCount;
extern int batteryCount;

///////////////////// VARIABLES ////////////////////
void upanim_Animation( lv_obj_t *TargetObject, int delay);
void hour_Animation( lv_obj_t *TargetObject, int delay);
void min_Animation( lv_obj_t *TargetObject, int delay);
void sec_Animation( lv_obj_t *TargetObject, int delay);
void scrolldot_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash( lv_event_t * e);
lv_obj_t *ui_Splash;
lv_obj_t *ui_Smart_Gadget;
lv_obj_t *ui_SLS_Logo;

int Selection;

// SCREEN: ui_Tikla
void ui_Tikla_screen_init(void);
lv_obj_t *ui_Tikla;
void ui_event_Start( lv_event_t * e);
lv_obj_t *ui_Start;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Image1;
void ui_event_Info( lv_event_t * e);
lv_obj_t *ui_Info;
lv_obj_t *ui_Label2;


// SCREEN: ui_Select
void ui_Select_screen_init(void);
lv_obj_t *ui_Select;
lv_obj_t *ui_Label3;
void ui_event_Ped( lv_event_t * e);
lv_obj_t *ui_Ped;
lv_obj_t *ui_Bandageamount;
lv_obj_t *ui_name;
lv_obj_t *ui_amountlabel;
void ui_event_Back( lv_event_t * e);
lv_obj_t *ui_Back;
lv_obj_t *ui_Label6;
void ui_event_Pastil( lv_event_t * e);
lv_obj_t *ui_Pastil;
lv_obj_t *ui_pastilamount;
lv_obj_t *ui_name1;
lv_obj_t *ui_amountlabel1;
void ui_event_Tooth( lv_event_t * e);
lv_obj_t *ui_Tooth;
lv_obj_t *ui_toothamount;
lv_obj_t *ui_name2;
lv_obj_t *ui_amountlabel2;
void ui_event_Battery( lv_event_t * e);
lv_obj_t *ui_Battery;
lv_obj_t *ui_Batteryamount;
lv_obj_t *ui_name3;
lv_obj_t *ui_amountlabel3;


// SCREEN: ui_Get_Info
void ui_Get_Info_screen_init(void);
void ui_event_Get_Info( lv_event_t * e);
lv_obj_t *ui_Get_Info;
void ui_event_Back2( lv_event_t * e);
lv_obj_t *ui_Back2;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Image9;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label12;


// SCREEN: ui_RFID
void ui_RFID_screen_init(void);
void ui_event_RFID( lv_event_t * e);
lv_obj_t *ui_RFID;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Image6;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label7;


// SCREEN: ui_Approve
void ui_Approve_screen_init(void);
void ui_event_Approve( lv_event_t * e);
lv_obj_t *ui_Approve;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Label14;


// SCREEN: ui_Reject
void ui_Reject_screen_init(void);
void ui_event_Reject( lv_event_t * e);
lv_obj_t *ui_Reject;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label13;
lv_obj_t *ui____initial_actions0;
const lv_image_dsc_t *ui_imgset_fezalogo[1] = {&ui_img_fezalogo2_png};
const lv_image_dsc_t *ui_imgset_universal_contactless_card_symbol[1] = {&ui_img_universal_contactless_card_symbol1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void upanim_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, -30, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 100);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void hour_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 2800 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void min_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 2100 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 200);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void sec_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 60000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 1000);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void scrolldot_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 30, -8 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Splash( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Tikla, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1400, &ui_Tikla_screen_init);
}
}
void ui_event_Start( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    getBalance();
      _ui_screen_change( &ui_Select, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Select_screen_init);
    char buffer[10];  // Değişkenleri string'e çevirmek için kullanılacak

    // breadCount'u ui_Bandageamount'a atama
    sprintf(buffer, "%d", breadCount);
    _ui_label_set_property( ui_pastilamount, _UI_LABEL_PROPERTY_TEXT, buffer);

    // pastaCount'u ui_pastilamount'a atama
    sprintf(buffer, "%d", pastaCount);
    _ui_label_set_property(ui_Bandageamount, _UI_LABEL_PROPERTY_TEXT, buffer);

    // diaperCount'u ui_toothamount'a atama
    sprintf(buffer, "%d", diaperCount);
    _ui_label_set_property(ui_toothamount, _UI_LABEL_PROPERTY_TEXT, buffer);

    // batteryCount'u ui_Batteryamount'a atama
    sprintf(buffer, "%d", batteryCount);
    _ui_label_set_property(ui_Batteryamount, _UI_LABEL_PROPERTY_TEXT, buffer);
}
}
void ui_event_Info( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Get_Info, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Get_Info_screen_init);
}
}
void ui_event_Ped( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    Selection = 3;
    //servoTurn(3,e); 
    _ui_screen_change( &ui_RFID, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RFID_screen_init);
}
}
void ui_event_Back( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    _ui_screen_change( &ui_Tikla, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Tikla_screen_init);
}
}
void ui_event_Pastil( lv_event_t * e) {
     
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    Selection = 2;
    //servoTurn(2,e);
    _ui_screen_change( &ui_RFID, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RFID_screen_init);
}
}
void ui_event_Tooth( lv_event_t * e) {
    
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    Selection = 1;
    //servoTurn(1,e); 
    _ui_screen_change( &ui_RFID, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RFID_screen_init);
}
}
void ui_event_Battery( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    Selection = 4;
    //servoTurn(4,e); 
    _ui_screen_change( &ui_RFID, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RFID_screen_init);
}
}
void ui_event_Get_Info( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_Select, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Select_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_RFID, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_RFID_screen_init);
}
}
void ui_event_Back2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Tikla, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Tikla_screen_init);
}
}
lv_timer_t * validation_timer;  // Zamanlayıcıyı tanımlayın

void validation_timer_cb(lv_timer_t * timer) {
    // Bu fonksiyon, ekran yüklendikten sonra çalıştırılacak
    bool success = validateCardData();
    if (success) {
        float mappedValue = getMappedValue(Selection);
        char buffer[10];
        dtostrf(mappedValue, 1, 2, buffer);  // float'ı const char*'a çevirir (1. basamak, 2 ondalık)

        sendTransaction(buffer);
        servoTurn(Selection, NULL); 

    // breadCount'u ui_Bandageamount'a atama
    sprintf(buffer, "%d", breadCount);
    _ui_label_set_property( ui_pastilamount, _UI_LABEL_PROPERTY_TEXT, buffer);

    // pastaCount'u ui_pastilamount'a atama
    sprintf(buffer, "%d", pastaCount);
    _ui_label_set_property(ui_Bandageamount, _UI_LABEL_PROPERTY_TEXT, buffer);

    // diaperCount'u ui_toothamount'a atama
    sprintf(buffer, "%d", diaperCount);
    _ui_label_set_property(ui_toothamount, _UI_LABEL_PROPERTY_TEXT, buffer);

    // batteryCount'u ui_Batteryamount'a atama
    sprintf(buffer, "%d", batteryCount);
    _ui_label_set_property(ui_Batteryamount, _UI_LABEL_PROPERTY_TEXT, buffer);
        _ui_screen_change(&ui_Approve, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Approve_screen_init);
    } else {
        _ui_screen_change(&ui_Reject, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Reject_screen_init);
    }

    lv_timer_del(timer);  // Zamanlayıcıyı yok et
}

void ui_event_RFID(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);

    if (event_code == LV_EVENT_PRESSED) {
        // Bu olayda bir işlem yapılmıyor, isterseniz ekleyebilirsiniz.
    }

    if (event_code == LV_EVENT_SCREEN_LOADED) {
        // Ekran yüklendiğinde zamanlayıcıyı başlatıyoruz
        validation_timer = lv_timer_create(validation_timer_cb, 1000, NULL);  // 1 saniye bekleyip çalışacak
    }
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Select, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Select_screen_init);
}
}
void ui_event_Approve( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Tikla, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3400, &ui_Tikla_screen_init);
}
}
void ui_event_Reject( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Tikla, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1400, &ui_Tikla_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_simple_init(dispp);
lv_disp_set_theme(dispp, theme);
ui_Splash_screen_init();
ui_Tikla_screen_init();
ui_Select_screen_init();
ui_Get_Info_screen_init();
ui_RFID_screen_init();
ui_Approve_screen_init();
ui_Reject_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Splash);
}
