// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: FezaESPArayuz

#ifndef _FEZAESPARAYUZ_UI_H
#define _FEZAESPARAYUZ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
bool validateCardData();
void getBalance();
void servoTurn(int eventCode, lv_event_t * e);
float getMappedValue(int input);
void sendTransaction(const char* id);
void upanim_Animation( lv_obj_t *TargetObject, int delay);
void hour_Animation( lv_obj_t *TargetObject, int delay);
void min_Animation( lv_obj_t *TargetObject, int delay);
void sec_Animation( lv_obj_t *TargetObject, int delay);
void scrolldot_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash( lv_event_t * e);
extern lv_obj_t *ui_Splash;
extern lv_obj_t *ui_Smart_Gadget;
extern lv_obj_t *ui_SLS_Logo;
// SCREEN: ui_Tikla
void ui_Tikla_screen_init(void);
extern lv_obj_t *ui_Tikla;
void ui_event_Start( lv_event_t * e);
extern lv_obj_t *ui_Start;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image1;
void ui_event_Info( lv_event_t * e);
extern lv_obj_t *ui_Info;
extern lv_obj_t *ui_Label2;
// SCREEN: ui_Select
void ui_Select_screen_init(void);
extern lv_obj_t *ui_Select;
extern lv_obj_t *ui_Label3;
void ui_event_Ped( lv_event_t * e);
extern lv_obj_t *ui_Ped;
extern lv_obj_t *ui_Bandageamount;
extern lv_obj_t *ui_name;
extern lv_obj_t *ui_amountlabel;
void ui_event_Back( lv_event_t * e);
extern lv_obj_t *ui_Back;
extern lv_obj_t *ui_Label6;
void ui_event_Pastil( lv_event_t * e);
extern lv_obj_t *ui_Pastil;
extern lv_obj_t *ui_pastilamount;
extern lv_obj_t *ui_name1;
extern lv_obj_t *ui_amountlabel1;
void ui_event_Tooth( lv_event_t * e);
extern lv_obj_t *ui_Tooth;
extern lv_obj_t *ui_toothamount;
extern lv_obj_t *ui_name2;
extern lv_obj_t *ui_amountlabel2;
void ui_event_Battery( lv_event_t * e);
extern lv_obj_t *ui_Battery;
extern lv_obj_t *ui_Batteryamount;
extern lv_obj_t *ui_name3;
extern lv_obj_t *ui_amountlabel3;
// SCREEN: ui_Get_Info
void ui_Get_Info_screen_init(void);
void ui_event_Get_Info( lv_event_t * e);
extern lv_obj_t *ui_Get_Info;
void ui_event_Back2( lv_event_t * e);
extern lv_obj_t *ui_Back2;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label12;
// SCREEN: ui_RFID
void ui_RFID_screen_init(void);
void ui_event_RFID( lv_event_t * e);
extern lv_obj_t *ui_RFID;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Image6;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label7;
// SCREEN: ui_Approve
void ui_Approve_screen_init(void);
void ui_event_Approve( lv_event_t * e);
extern lv_obj_t *ui_Approve;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label14;
// SCREEN: ui_Reject
void ui_Reject_screen_init(void);
void ui_event_Reject( lv_event_t * e);
extern lv_obj_t *ui_Reject;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_fezalogo2_png);   // assets/fezalogo2.png
LV_IMG_DECLARE( ui_img_pattern_png);   // assets/pattern.png
LV_IMG_DECLARE( ui_img_universal_contactless_card_symbol1_png);   // assets/Universal_Contactless_Card_Symbol1.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
