// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: FezaESPArayuz

#include "ui.h"

void tikla(lv_event_t * e)
{
	// Your code here
}
