// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: FezaESPArayuz

#include "ui.h"

void ui_Get_Info_screen_init(void)
{
ui_Get_Info = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Get_Info, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_Get_Info, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_tiled(ui_Get_Info, true, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back2 = lv_button_create(ui_Get_Info);
lv_obj_set_width( ui_Back2, 272);
lv_obj_set_height( ui_Back2, 50);
lv_obj_set_x( ui_Back2, 0 );
lv_obj_set_y( ui_Back2, 193 );
lv_obj_set_align( ui_Back2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Back2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Back2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Back2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Back2, lv_color_hex(0x395994), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Back2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Back2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Back2);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Back");

ui_Image9 = lv_image_create(ui_Get_Info);
lv_image_set_src(ui_Image9, &ui_img_fezalogo2_png);
lv_obj_set_width( ui_Image9, lv_pct(10));
lv_obj_set_height( ui_Image9, lv_pct(10));
lv_obj_set_x( ui_Image9, -105 );
lv_obj_set_y( ui_Image9, -163 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image9,30);

ui_Label4 = lv_label_create(ui_Get_Info);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -22 );
lv_obj_set_y( ui_Label4, -182 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"YAZGIT Feza");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Get_Info);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 45 );
lv_obj_set_y( ui_Label11, -156 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"End-to-End Physical Donations \nwith Blockchain and DID Technology");
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Get_Info);
lv_obj_set_width( ui_Panel1, 272);
lv_obj_set_height( ui_Panel1, 268);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, 20 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xA4C6C5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label12, lv_pct(88));
lv_obj_set_height( ui_Label12, lv_pct(90));
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"The YAZGIT Feza team was established in 2024 under the Konya Technical University Artificial Intelligence and Image Processing Society. The team consists of one academic advisor and three dedicated members. Our goal is to integrate blockchain technology into modern life by developing a contemporary donation mechanism. We aim to create reliable and transparent donation processes. Each team member has specific roles in their respective fields, with detailed descriptions provided alongside.");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x626562), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Back2, ui_event_Back2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Get_Info, ui_event_Get_Info, LV_EVENT_ALL, NULL);

}
