// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: FezaESPArayuz

#include "ui.h"

void ui_Splash_screen_init(void)
{
ui_Splash = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Splash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Smart_Gadget = ui_Small_Label_create(ui_Splash);
lv_obj_set_x( ui_Smart_Gadget, 0 );
lv_obj_set_y( ui_Smart_Gadget, 136 );
lv_obj_set_align( ui_Smart_Gadget, LV_ALIGN_CENTER );
lv_label_set_text(ui_Smart_Gadget,"End-to-End Physical Donations \nwith Blockchain and \nDID Technology");
lv_obj_set_style_text_color(ui_Smart_Gadget, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Smart_Gadget, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Smart_Gadget, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Smart_Gadget, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SLS_Logo = lv_image_create(ui_Splash);
lv_image_set_src(ui_SLS_Logo, &ui_img_fezalogo2_png);
lv_obj_set_width( ui_SLS_Logo, 200);
lv_obj_set_height( ui_SLS_Logo, 200);
lv_obj_set_x( ui_SLS_Logo, 1 );
lv_obj_set_y( ui_SLS_Logo, -51 );
lv_obj_set_align( ui_SLS_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SLS_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_SLS_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_SLS_Logo,150);

lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}
