// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: FezaESPArayuz

#include "ui.h"

void ui_Select_screen_init(void)
{
ui_Select = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Select, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Select, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Select, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_Select, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_tiled(ui_Select, true, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Select);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 0 );
lv_obj_set_y( ui_Label3, -200 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Select a Product");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Ped = lv_button_create(ui_Select);
lv_obj_set_width( ui_Ped, 125);
lv_obj_set_height( ui_Ped, 125);
lv_obj_set_x( ui_Ped, -73 );
lv_obj_set_y( ui_Ped, -64 );
lv_obj_set_align( ui_Ped, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Ped, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Ped, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Ped, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Ped, lv_color_hex(0xA1C5C7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Ped, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bandageamount = lv_label_create(ui_Ped);
lv_obj_set_width( ui_Bandageamount, LV_SIZE_CONTENT);  /// 2
lv_obj_set_height( ui_Bandageamount, LV_SIZE_CONTENT);   /// 2
lv_obj_set_x( ui_Bandageamount, 0 );
lv_obj_set_y( ui_Bandageamount, 30 );
lv_obj_set_align( ui_Bandageamount, LV_ALIGN_CENTER );
lv_label_set_text(ui_Bandageamount,"text");

ui_name = lv_label_create(ui_Ped);
lv_obj_set_width( ui_name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_name, 0 );
lv_obj_set_y( ui_name, -20 );
lv_obj_set_align( ui_name, LV_ALIGN_CENTER );
lv_label_set_text(ui_name,"Bandage");
lv_obj_set_style_text_color(ui_name, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_amountlabel = lv_label_create(ui_Ped);
lv_obj_set_width( ui_amountlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_amountlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_amountlabel, 0 );
lv_obj_set_y( ui_amountlabel, 10 );
lv_obj_set_align( ui_amountlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_amountlabel,"Amount:");

ui_Back = lv_button_create(ui_Select);
lv_obj_set_width( ui_Back, 272);
lv_obj_set_height( ui_Back, 50);
lv_obj_set_x( ui_Back, 0 );
lv_obj_set_y( ui_Back, 193 );
lv_obj_set_align( ui_Back, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Back, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Back, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Back, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Back, lv_color_hex(0x395994), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Back);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Back");

ui_Pastil = lv_button_create(ui_Select);
lv_obj_set_width( ui_Pastil, 125);
lv_obj_set_height( ui_Pastil, 125);
lv_obj_set_x( ui_Pastil, 73 );
lv_obj_set_y( ui_Pastil, -64 );
lv_obj_set_align( ui_Pastil, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Pastil, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Pastil, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Pastil, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Pastil, lv_color_hex(0xA1C5C7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pastil, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pastilamount = lv_label_create(ui_Pastil);
lv_obj_set_width( ui_pastilamount, LV_SIZE_CONTENT);  /// 2
lv_obj_set_height( ui_pastilamount, LV_SIZE_CONTENT);   /// 2
lv_obj_set_x( ui_pastilamount, 0 );
lv_obj_set_y( ui_pastilamount, 30 );
lv_obj_set_align( ui_pastilamount, LV_ALIGN_CENTER );
lv_label_set_text(ui_pastilamount,"text");

ui_name1 = lv_label_create(ui_Pastil);
lv_obj_set_width( ui_name1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_name1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_name1, 0 );
lv_obj_set_y( ui_name1, -20 );
lv_obj_set_align( ui_name1, LV_ALIGN_CENTER );
lv_label_set_text(ui_name1,"Pastil");
lv_obj_set_style_text_color(ui_name1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_name1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_amountlabel1 = lv_label_create(ui_Pastil);
lv_obj_set_width( ui_amountlabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_amountlabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_amountlabel1, 0 );
lv_obj_set_y( ui_amountlabel1, 10 );
lv_obj_set_align( ui_amountlabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_amountlabel1,"Amount:");

ui_Tooth = lv_button_create(ui_Select);
lv_obj_set_width( ui_Tooth, 125);
lv_obj_set_height( ui_Tooth, 125);
lv_obj_set_x( ui_Tooth, 73 );
lv_obj_set_y( ui_Tooth, 84 );
lv_obj_set_align( ui_Tooth, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Tooth, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Tooth, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Tooth, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Tooth, lv_color_hex(0xA1C5C7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Tooth, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_toothamount = lv_label_create(ui_Tooth);
lv_obj_set_width( ui_toothamount, LV_SIZE_CONTENT);  /// 2
lv_obj_set_height( ui_toothamount, LV_SIZE_CONTENT);   /// 2
lv_obj_set_x( ui_toothamount, 0 );
lv_obj_set_y( ui_toothamount, 30 );
lv_obj_set_align( ui_toothamount, LV_ALIGN_CENTER );
lv_label_set_text(ui_toothamount,"text");

ui_name2 = lv_label_create(ui_Tooth);
lv_obj_set_width( ui_name2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_name2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_name2, 0 );
lv_obj_set_y( ui_name2, -20 );
lv_obj_set_align( ui_name2, LV_ALIGN_CENTER );
lv_label_set_text(ui_name2,"Tooth Paste");
lv_obj_set_style_text_color(ui_name2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_name2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_amountlabel2 = lv_label_create(ui_Tooth);
lv_obj_set_width( ui_amountlabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_amountlabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_amountlabel2, 0 );
lv_obj_set_y( ui_amountlabel2, 10 );
lv_obj_set_align( ui_amountlabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_amountlabel2,"Amount:");

ui_Battery = lv_button_create(ui_Select);
lv_obj_set_width( ui_Battery, 125);
lv_obj_set_height( ui_Battery, 125);
lv_obj_set_x( ui_Battery, -73 );
lv_obj_set_y( ui_Battery, 84 );
lv_obj_set_align( ui_Battery, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Battery, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Battery, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Battery, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0xA1C5C7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Batteryamount = lv_label_create(ui_Battery);
lv_obj_set_width( ui_Batteryamount, LV_SIZE_CONTENT);  /// 2
lv_obj_set_height( ui_Batteryamount, LV_SIZE_CONTENT);   /// 2
lv_obj_set_x( ui_Batteryamount, 0 );
lv_obj_set_y( ui_Batteryamount, 30 );
lv_obj_set_align( ui_Batteryamount, LV_ALIGN_CENTER );
lv_label_set_text(ui_Batteryamount,"text");

ui_name3 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_name3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_name3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_name3, 0 );
lv_obj_set_y( ui_name3, -20 );
lv_obj_set_align( ui_name3, LV_ALIGN_CENTER );
lv_label_set_text(ui_name3,"Battary");
lv_obj_set_style_text_color(ui_name3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_name3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_amountlabel3 = lv_label_create(ui_Battery);
lv_obj_set_width( ui_amountlabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_amountlabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_amountlabel3, 0 );
lv_obj_set_y( ui_amountlabel3, 10 );
lv_obj_set_align( ui_amountlabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_amountlabel3,"Amount:");

lv_obj_add_event_cb(ui_Ped, ui_event_Ped, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Back, ui_event_Back, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Pastil, ui_event_Pastil, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Tooth, ui_event_Tooth, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Battery, ui_event_Battery, LV_EVENT_ALL, NULL);

}
