// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: FezaESPArayuz

#include "ui.h"

void ui_Tikla_screen_init(void)
{
ui_Tikla = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Tikla, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_Tikla, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_tiled(ui_Tikla, true, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Start = lv_button_create(ui_Tikla);
lv_obj_set_width( ui_Start, 200);
lv_obj_set_height( ui_Start, 50);
lv_obj_set_x( ui_Start, -2 );
lv_obj_set_y( ui_Start, 93 );
lv_obj_set_align( ui_Start, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Start, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Start, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Start, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Start, lv_color_hex(0x63815C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Start, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Start, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Start);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Start!");

ui_Image1 = lv_image_create(ui_Tikla);
lv_image_set_src(ui_Image1, &ui_img_fezalogo2_png);
lv_obj_set_width( ui_Image1, lv_pct(60));
lv_obj_set_height( ui_Image1, lv_pct(60));
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, -88 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image1,150);

ui_Info = lv_button_create(ui_Tikla);
lv_obj_set_width( ui_Info, 200);
lv_obj_set_height( ui_Info, 50);
lv_obj_set_x( ui_Info, -1 );
lv_obj_set_y( ui_Info, 158 );
lv_obj_set_align( ui_Info, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Info, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Info, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Info, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Info, lv_color_hex(0x395B91), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Info, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Info, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Info);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Get Info");

lv_obj_add_event_cb(ui_Start, ui_event_Start, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Info, ui_event_Info, LV_EVENT_ALL, NULL);

}
